### ISSUE TITLE
Update copyright year

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/lesson-example#106]
The lesson websites still say `(c) 2016`. Unless this is intended, can the year be updated automatically? Alternatively, there should maybe be a range - 20XX - 2017 with XX the first year the lesson was available.

Same issue applies to the training template https://github.com/swcarpentry/training-template.

**Comment by rgaiacs** [comment]
@lexnederbragt Thanks for the issue. It is implemented at https://github.com/swcarpentry/styles/pull/135 and will be on the lessons next time that we update the styles (probably this weekend).
