### ISSUE TITLE
Make challenges appear open by default

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/lesson-example#113]
With the challenges being click to open, there has been some confusion about where the challenges are until people realize they need to click on the arrow.

In the Data Carpentry lessons and now in the instructor training lessons, the behavior of the challenges has been changed, so that the default is that they are open rather than closed. Should that be the default behavior in the template?

This is modified is assets/js/lesson.js

**Comment by rgaiacs** [comment]
> With the challenges being click to open, there has been some confusion about where the challenges are until people realize they need to click on the arrow.

I don't have any training in user experience/user interface so I can't what we should use and I fail to locate the issue where I and @gvwilson talked about hide or not the challenges and other call out boxes. What I remember is that the decision to hide challenges and call out boxes was to not "distract" self-learners and workshop attendees from the main lesson/text.

> Should that be the default behavior in the template?

I think that all Carpentry lessons should have the same fell. We should hide challenges in all or don't do it in any.

If people prefer to have un-hide challenges by default I would request to un-hide all the call out boxes for sake of consistence and reduce our code base.

**Comment by tracykteal** [comment]
Thanks @rgaiacs then I would advocate for unhiding them by default. In discussion sections we've had people mention it as an issue. Since they already look separate in their box, they don't seem to be a distraction in the flow of reading. Happy to put in a PR if this is the decision.

**Comment by rgaiacs** [comment]
> Happy to put in a PR if this is the decision.

I can do the PR but I want to ask more people about their preferences. I will copy you on the email.

**Comment by tracykteal** [comment]
As a note, I think we should keep the 'hide' option. It's good for the 'solutions'. It just seems less useful for the 'challenge' and maybe also 'discussion'.

**Comment by gdevenyi** [comment]
I'm okay with show by default with a hide button

**Comment by orchid00** [comment]
I like to show challenges by default and hide solutions by default. The aliases example looks good @tracykteal

**Comment by gcapes** [comment]
I think the solutions should be within the challenge callout box - as they currently are. This looks neater. The SQL lesson has them as a separate box. 

I don't feel strongly about whether the question is shown or hidden by default, or whether it is hidable at all.

**Comment by tracykteal** [comment]
You're right it is better to have them together and agree that should be the default. I put in a PR. That update is viewable here http://tracykteal.github.io/sql-ecology/03-sql-joins-aliases/

**Comment by naupaka** [comment]
I'm +1 for challenge shown by default and answers to challenges hidden by default.

**Comment by tbekolay** [comment]
I'm also +1 for challenges shown by default and solutions hidden by default.

Not to veer too off-topic, but it might also be nice to provide a "show / hide all challenges" link to show or hide all challenges at once.

**Comment by rgaiacs** [comment]
So far the we have

# Show by default (with questions hide)

- @tracykteal
- @gdevenyi
- @orchid00
- @naupaka
- @tbekolay

# Resolution

I'm sending a pull request soon.

**Comment by rgaiacs** [comment]
Close by #120.
