### ISSUE TITLE
printing the whole lesson

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/lesson-example#117]
Some instructors, me included, like to print out the lessons to teach from them. Right now, this means that you have to go to each episode individually and print it. It might be nice if there was a  way to print out the whole lesson.

**Comment by rgaiacs** [comment]
Maybe we should try to use client side Javascript to download all the episodes, copy the content and paste it in only one webpage.

**Comment by rgaiacs** [comment]
Close by #120.
