### ISSUE TITLE
Need to use checkpoint:::scanForPackages() in Rmd build script 

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/lesson-example#118]
When running `make lesson-md` locally, the following warning appears (script in question is `bin/generate_md_episodes.R` on line 11):

```
Warning message:
In checkpoint:::projectScanPackages(project = "_episodes_rmd", verbose = FALSE,  :
  Use checkpoint:::scanForPackages() instead
```

The code to be changed is [here](https://github.com/swcarpentry/r-novice-gapminder/blob/gh-pages/bin/generate_md_episodes.R#L11). Seems like it should be changed here in lesson-template repo, since it will also affect r-novice-inflammation.

**Comment by rgaiacs** [comment]
Thanks to @fmichonneau for the pull request. @naupaka should I send a pull request to the R lessons? Or could you do that?

**Comment by naupaka** [comment]
@rgaiacs I've never done that with imported (vs forked) repos. How do I create the proper PR?

**Comment by rgaiacs** [comment]
@naupaka I wrote a shell script to do it last time that I had to perform such task: https://github.com/swcarpentry/infra-lessons/blob/master/setup.sh and https://github.com/swcarpentry/infra-lessons/blob/master/propagate.sh. It should give you an idea. I could do it tomorrow after I merge https://github.com/swcarpentry/styles/issues/144, https://github.com/swcarpentry/styles/pull/143, https://github.com/swcarpentry/styles/pull/142, https://github.com/swcarpentry/lesson-example/pull/119, https://github.com/swcarpentry/lesson-example/pull/116.

**Comment by naupaka** [comment]
Looks a little tricky. If you can submit the PR to the R lessons, I will merge.
