### ISSUE TITLE
"Creating lesson" presentation refers to deprecated motivation.md 

### ISSUE THREAD

**Issue by alex-konovalov** [swcarpentry/lesson-example#12]
I've discovered that [this slide](http://swcarpentry.github.io/slideshows/creating-lesson/index.html#slide-24) still refers to `motivation.md` which seems to be deprecated as a result of PR #10. 

I can't find the source for the "Creating lesson" presentation, so decided to report it in the place where `motivation.md` existed before.

**Comment by alex-konovalov** [comment]
Just to remind - I could turn this into PR if anyone could point me to the source of the slideshow in question. Thanks.

**Comment by wking** [comment]
On Wed, Dec 02, 2015 at 03:46:52PM -0800, Alexander Konovalov wrote:
> I could turn this into PR if anyone could point me to the source of
> the slideshow in question.

It's probably in here [1].  But a little GitHub banner linking from
the compiled page to that repository would be nice.

[1]: https://github.com/swcarpentry/slideshows

**Comment by alex-konovalov** [comment]
@wking Thanks. I've made PR https://github.com/swcarpentry/slideshows/pull/27 and created issue https://github.com/swcarpentry/slideshows/issues/28 there.
