### ISSUE TITLE
bin/test_lesson_check.py fails with syntax error

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/lesson-example#121]
When I ran

~~~
$ ./bin/test_lesson_check.py
~~~

I got

~~~
./bin/test_lesson_check.py: line 6: syntax error near unexpected token `('
./bin/test_lesson_check.py: line 6: `class TestFileList(unittest.TestCase):'
~~~

Despite the permissions

~~~
$ ls -l bin/test_lesson_check.py 
-rwxr-xr-x 1 raniere raniere 609 Mar 28 10:00 bin/test_lesson_check.py*
~~~

the file doesn't mention which script interpreter it need to use

~~~
$ head bin/test_lesson_check.py 
import unittest

import lesson_check
import util

class TestFileList(unittest.TestCase):
    def setUp(self):
        self.reporter = util.Reporter()  ## TODO: refactor reporter class.

    def test_file_list_has_expected_entries(self):
~~~

@gvwilson Any reason to not include

~~~
#!/usr/bin/env python 
~~~

I would like to (1) include the previous line or (2) remove the execution permission.

**Comment by naught101** [comment]
Also hitting this. +1 for the shebang.

**Comment by rgaiacs** [comment]
I think this in the line of another issue that I opened in the past.

@gvwilson is a **big** fan of Make and wrap everything in a `Makefile`. You and I (and everyone) should be using

~~~
$ make lesson-check-all
~~~

instead of 

~~~
$ ./bin/test_lesson_check.py
~~~

See https://github.com/swcarpentry/lesson-example/blob/gh-pages/Makefile#L91 for details.

I don't like the name `bin` when you can't use run the files so I need to think about a better name like `stay-away`. :-) I'm closing this for now.
