### ISSUE TITLE
Add bin/README.md

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/lesson-example#122]
Calling some scripts from `bin/` directly instead of using the `Makefile` wrapper can create problems.

@gvwilson @k8hertweck @tracykteal @wking Any objections to include `bin/README.md` mentioning that all the scripts should be called from the `Makefile`?

**Comment by gvwilson** [comment]
No objection, but I doubt people will see it - point 6 in the lesson example's README.md is `run lesson-check`, so if there's a way to draw more attention to that...

**Comment by rgaiacs** [comment]
I'm closing this since it is documented in `README.md`.
