### ISSUE TITLE
Where to store images?

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/lesson-example#129]
[Lesson Organisation](http://swcarpentry.github.io/lesson-example/03-organization/) doesn't cover where to store images! **We should fix this as soon as possible.**

**Comment by naupaka** [comment]
For r-novice-gapminder we have all of ours in `fig/`. Seems like a reasonable place to me.

**Comment by iglpdc** [comment]
Same thing for git-novice: `fig/`.

**Comment by rgaiacs** [comment]
@naupaka and @iglpdc Thanks. #137 should fix this issue.
