### ISSUE TITLE
navbar.html links

### ISSUE THREAD

**Issue by jcoliver** [swcarpentry/lesson-example#148]
In _includes/navbar.html, the links are slightly different from other lessons. For example, in this template, the link to the setup instructions is given by:
`<li><a href="{{ page.root }}{% link setup.md %}">Setup</a></li>`
This ultimately renders to http://swcarpentry.github.io/lesson-example/setup.html
In contrast, the R gapminder and git lessons have the link in _includes/navbar.html as:
`<li><a href="{{ page.root }}/setup/">Setup</a></li>`

Note index.md in lesson-example uses the syntax as other sites do in the leading text (the text immediately underneath the "Lesson Title"), but the link does not resolve (404). The text in index.md is: "...for guidelines on how to set up your machine to preview changes locally, please see [the setup instructions](http://swcarpentry.github.io/lesson-example/setup/)" 

I'm not sure the best means of resolving this, but a quick fix would be to update the link to the setup instructions in the beginning text.
Change: http://swcarpentry.github.io/lesson-example/setup/
To: http://swcarpentry.github.io/lesson-example/setup.html

**Comment by rgaiacs** [comment]
Hi @jcoliver,

Thanks for the issue.

> In _includes/navbar.html, the links are slightly different from other lessons. For example, in this > template, the link to the setup instructions is given by:
> `<li><a href="{{ page.root }}{% link setup.md %}">Setup</a></li>`
> This ultimately renders to http://swcarpentry.github.io/lesson-example/setup.html
> In contrast, the R gapminder and git lessons have the link in _includes/navbar.html as:
> `<li><a href="{{ page.root }}/setup/">Setup</a></li>`

This is one of the changes that the new release is going to introduce. The `link` function (tag is the name used in Liquid documentation) will avoid us to make mistake in the future with links.

@brucellino sent a pull request to fix this, https://github.com/swcarpentry/lesson-example/pull/147.
