### ISSUE TITLE
Removing _includes/all_figures.html gives error

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/lesson-example#153]
Following 6, 

> 6. Remove _includes/all_figures.html because we don't need the file any more. 

I get this error:
`Liquid Exception: Could not locate the included file 'all_figures.html' in any of ["make-novice/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in make-novice/_extras/figures.md
`

**Comment by gcapes** [comment]
Jekyll version 3.6.2

**Comment by rgaiacs** [comment]
@gcapes Thanks for the report.

Could you check `_extras/figures.md`. https://github.com/swcarpentry/lesson-example/commit/a09dae854df933435827b2fd43a1d7186d234db6 should have change it to remove

~~~
{% include all_figures.html %}
~~~

And `_includes/all_figures.html` should not be used by another file.

**Comment by gcapes** [comment]
That's the problem, yes. That commit is missing from my repo. If I simply delete that line from `_extras/figures.md`, I get no jekyll error. However I'm not sure if there is some other problem I haven't noticed.

To do it properly, do I just add the lesson example as a remote and cherry-pick that commit?

**Comment by rgaiacs** [comment]
Hi @gcapes, Thanks very much for the report. a09dae8 exists in https://github.com/swcarpentry/lesson-example/ but not in https://github.com/swcarpentry/styles. My mistake. :-( I made t[his release, v9.3.1](https://github.com/swcarpentry/styles/releases/tag/v9.3.1) that include the changes on `_extras/figures.md`. If you fetch https://github.com/swcarpentry/styles and merge it into your local copy the error should be fixed. I will let this issue open for know. Please close it when you have time to incorporate v9.3.1.

**Comment by gcapes** [comment]
It was a bit of a git workout, but I think that's all done now! Perhaps you could have a quick look at the site to double check?
Thanks

**Comment by rgaiacs** [comment]
As I mentioned [here](https://github.com/swcarpentry/styles/pull/193), there correct thing is to cherry-pick the commit a09dae8 but it will require you to add this repository as remote. :-(

**Comment by naupaka** [comment]
@rgaiacs I got the same error on r-novice-gapminder with 9.3.0, but it works fine after merging in 9.3.1

**Comment by rgaiacs** [comment]
@naupaka Thanks for the feedback. Let me know if any action from me is needed.
