### ISSUE TITLE
syntax highlighting not working in some repos

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/lesson-example#169]
During Maintainer onboarding today we were testing adding the new language specific tags to the code chunks to turn on syntax highlighting, however, it did not produce the desired result. 

We tested adding .language-sql to the SWC SQL lesson code chunks and it only turned the code chunk grey (removed the purple side bar that was present on the code chunk), but did not add any coloration or styling to the SQL keywords.

The same was true in the SWC Python Novice Gapminder (Plotting and Programming with Python) lesson. There was no change after adding the .language-python tag other than turning the code chunk grey. 

As a group, the new Maintainers would like to check what they can do to make sure that syntax highlighting is working in their repositories. Any suggestions?

**Comment by rgaiacs** [comment]
> We tested adding .language-sql to the SWC SQL lesson code chunks and it only turned the code chunk grey (removed the purple side bar that was present on the code chunk)

This is related with https://github.com/swcarpentry/styles/pull/202. I need to find some time to merge it and do all the other release-related tasks. :-(

> but did not add any coloration or styling to the SQL keywords.
>
> The same was true in the SWC Python Novice Gapminder (Plotting and Programming with Python) lesson. There was no change after adding the .language-python tag other than turning the code chunk grey.

If you go to "Change an Existing Cell from Code to Markdown" at https://rgaiacs.github.io/swc-python-novice-gapminder/01-run-quit/ you will find the `print` function in green. The problem, as demonstrated in https://github.com/rgaiacs/swc-python-novice-gapminder/commits/gh-pages, is that the Gapminder lesson didn't merge the latest release of https://github.com/swcarpentry/styles. You can merge my branch or

~~~
$ git remote add styles git@github.com:swcarpentry/styles.git
$ git fetch styles
$ git merge styles:gh-pages
$ git push origin gh-pages
~~~

https://github.com/swcarpentry/infra-lessons has some instructions to create pull request to many lessons.

**Comment by rgaiacs** [comment]
This is fixed.
