### ISSUE TITLE
Following instructions leads you between lesson-template and lesson-example, where is the README?

### ISSUE THREAD

**Issue by arokem** [swcarpentry/lesson-example#17]
The github importer link gets you the lesson-template repo. Then, step 10, sends you over here, where you are informed that you should have README file in your repo, but at this point, you don't have a README file, because lesson-template doesn't have that. At which point you start questioning yourself: have I misunderstood these instructions?

**Comment by arokem** [comment]
Sorry - edited the title of this issue to be less hysteric. Apologies for the initial trollish-ness.

**Comment by wking** [comment]
On Fri, Jan 08, 2016 at 03:48:34PM -0800, Ariel Rokem wrote:
> The github importer link gets you the lesson-template repo. Then,
> step 10, sends you over here, where you are informed that you should
> have README file in your repo…

Step 10 from the README is [1]:

  Create and edit files as explained in Lesson Layout [2], Background
  and Design [3], and the FAQ [4].

That suggests you should be *creating* and editing the files.  In [2],
there's:

  README.md: initially a copy of this repository's README file. It
  should be overwritten…

which is wrong (probably just left over from when the template
included a README, which was missed in 3eaab252a).  I suggest updating
that entry to:

  README.md: A short description of the lesson.  Please include the
  following blockquote to help people find these instructions…

[1]: https://github.com/swcarpentry/lesson-example#creating-your-lessons-repository
[2]: https://github.com/swcarpentry/lesson-example/blob/gh-pages/LAYOUT.md
[3]: https://github.com/swcarpentry/lesson-example/blob/gh-pages/DESIGN.md
[4]: https://github.com/swcarpentry/lesson-example/blob/gh-pages/FAQ.md

**Comment by arokem** [comment]
Yup. That's exactly my issue, explained more clearly, and offering a solution. So useful. PR to follow.

**Comment by gvwilson** [comment]
Closed by #18.
