### ISSUE TITLE
Avoid "Click Here" for links

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/lesson-example#175]
@katrinleinweber mentioned https://webaccess.berkeley.edu/ask-pecan/click-here. This information should go into http://swcarpentry.github.io/lesson-example/06-style-guide/index.html.

@katrinleinweber could you send a pull request with a new section to http://swcarpentry.github.io/lesson-example/06-style-guide/index.html? Maybe something like

> ## Links
>
> Avoid use "click here" for links because .... Instead use ... For example, ...

**Comment by katrinleinweber** [comment]
Will do! Please assign me this issue so I have a backup to keeping the browser tab open until I have time on the weekend ;-)

**Comment by rgaiacs** [comment]
@katrinleinweber I can't assign you. I would love to bu t GitHub doesn't allow me. This is one of the missing features that I hate GitHub to not implement.

**Comment by rgaiacs** [comment]
> I assumed you were this repo's maintainer.

I'm one of the maintainers.

> It must be related to that, because in r-novice, I can edit metadata of issues I did not start.

I can edit metadata but as I said the problem is GitHub.

![screenshot from 2018-02-15 11-21-21](https://user-images.githubusercontent.com/1506457/36254358-c30140d0-1242-11e8-8be3-a84bc3490c6b.png)

GitHub doesn't allow me to assign it you your user.

![screenshot from 2018-02-15 11-21-40](https://user-images.githubusercontent.com/1506457/36254378-ce8c6b50-1242-11e8-9f09-73e443e8b482.png)

You can only assign issues to users with write access to the repository. And I can't change this.
