### ISSUE TITLE
Needs fixes for many broken links in lesson-example/CONTRIBUTING.md

### ISSUE THREAD

**Issue by krishnakumarg1984** [swcarpentry/lesson-example#182]
In https://github.com/swcarpentry/lesson-example/blob/gh-pages/CONTRIBUTING.md, there are lots of broken links. 

All broken links point downstream from https://github.com/swcarpentry/FIXME

In **How to Contribute**
If you have a GitHub account, or are willing to create one, but do not know how to use Git, you can report problems or suggest improvements by creating an issue. This allows us to assign the item to someone and to respond to it in a threaded discussion.

The link https://github.com/swcarpentry/FIXME/issues/ is broken

In **Where to Contribute**
1. If you wish to change this lesson, please work in https://github.com/swcarpentry/FIXME, which can be viewed at https://swcarpentry.github.io/FIXME.

Both these links are broken.

In **What to Contribute**
There are many ways to contribute, from writing new exercises and improving existing ones to updating or filling in the documentation and and submitting bug reports about things that don't work, aren't clear, or are missing.  If you are looking for ideas, please see the list of issues for this repository, or the issues for Data Carpentry and Software Carpentry projects.

The link for submitting bug reports as well as for list of issues (https://github.com/swcarpentry/FIXME/issues/) does not work.

In **Using Github**
The published copy of the lesson is in the gh-pages branch of the repository (so that GitHub will regenerate it automatically). Please create all branches from that, and merge the master repository's gh-pages branch into your gh-pages branch before starting work. Please do not work directly in your gh-pages branch, since that will make it difficult for you to work on other contributions.

Again, the link to master repository (https://github.com/swcarpentry/FIXME/) is broken

**Comment by rgaiacs** [comment]
> In https://github.com/swcarpentry/lesson-example/blob/gh-pages/CONTRIBUTING.md, there are lots of broken links.

Thanks. This is probably because I run https://github.com/swcarpentry/lesson-example/blob/gh-pages/bin/lesson_initialize.py#L18 and replace the file last time without notice the `FIXME` words. I don't like https://github.com/swcarpentry/lesson-example/blob/gh-pages/bin/lesson_initialize.py#L18 and I still looking for a way to replace it.

**Comment by krishnakumarg1984** [comment]
Ok... Understood.

But this is the guidelines for contributing page and for a newcomer like me, it confuses me to see lot of broken links.

How would you propose to close this issue?
________________________________

**Comment by rgaiacs** [comment]
> How would you propose to close this issue?

A pull request with the correct link is welcome. Or I will fix in a few days.

**Comment by krishnakumarg1984** [comment]
Thank you. I shall read the instructions on how to and begin to work on 
a pull request.

This is going to be my first ever pull request for any open source 
project. Can this be counted towards my instructor training checkout?

Regards,

Krishnakumar

**Comment by rgaiacs** [comment]
> Can this be counted towards my instructor training checkout?

I think yes. @ErinBecker ?

**Comment by ErinBecker** [comment]
Absolutely! This is a valuable contribution. Can you please send an email to checkout@carpentries.org with a link to this issue so we can record your contribution?

**Comment by krishnakumarg1984** [comment]
@ErinBecker  and @rgaiacs  thank you very much. It was a bit of a learning curve to do the pull request, but I think I have done it now.

Please review this PR #184  and let me know if more work is required. Thanks for your support.

**Comment by krishnakumarg1984** [comment]
Many thanks for accepting my PR #184 .
