### ISSUE TITLE
Copyright information

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/lesson-example#193]
The lessons, because of the template, have "Copyright © 2016–2018 Software Carpentry Foundation" in the footnote. Because of the merge and the move to a new financial sponsor, is the copyright information still correct?

@tracykteal I need your word on this.

**Comment by tracykteal** [comment]
Thanks @rgaiacs. We should update the copyright information to "Copyright © 2018 The Carpentries"

**Comment by rgaiacs** [comment]
Close by https://github.com/swcarpentry/styles/pull/239.
