### ISSUE TITLE
non-fast-forward error message when doing first commit

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/lesson-example#52]
After cloning the imported version, running lesson_initialize.py and editing an _episodes file, when you go to push, you get a 'non-fast-forward' git error message

"
git push origin gh-pages
To https://github.com/tracykteal/lesson-lesson
 ! [rejected]        gh-pages -> gh-pages (non-fast-forward)
error: failed to push some refs to 'https://github.com/tracykteal/lesson-lesson'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
"

It's fixable with a
- git fetch origin
- git merge origin gh-pages
- git pull origin gh-pages

but it would be nice to avoid the error

**Comment by gvwilson** [comment]
I don't get this error - if I understand correctly, you are doing this:

1. Use GitHub import to create a new lesson-foo repository that you own.
2. `git clone git@github.com:your_id/lesson-foo.git`
3. `cd lesson-foo`
4. `vim _episodes/01-example.md`
5. `git add _episodes/01-example.md`
6. `git commit -m "starting"`
7. `git push origin gh-pages`

Is that correct?

**Comment by rgaiacs** [comment]
@tracykteal Do you have any update on this one?

**Comment by rgaiacs** [comment]
I'm closing this as out of date.
