### ISSUE TITLE
missing image file in setup.md

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/lesson-example#53]
In setup.md under 'Creating a lesson' point 7, there's a missing image file

**Comment by rgaiacs** [comment]
The missing image is https://github.com/swcarpentry/lesson-example/blob/gh-pages/fig/using-github-import.png. The image is missing because we used `{{ site.github.url }}/fig/using-github-import.png``and GitHub don't use the YAML file.

**Comment by gvwilson** [comment]
Image is showing up for me at http://swcarpentry.github.io/lesson-example/setup/ - @tracykteal can you please confirm?

**Comment by tracykteal** [comment]
looks good
