### ISSUE TITLE
{: .source} tags appear in setup.md

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/lesson-example#54]
The {: .source} tags are appearing in setup.md rather than providing formatting.

**Comment by rgaiacs** [comment]
GitHub uses different Markdown processors for GitHub Pages and GitHub file preview. **I would close this as won't fix.**

**Comment by gvwilson** [comment]
As @rgaiacs says, this renders on GitHub Pages and when Jekyll is run locally.
