### ISSUE TITLE
An example Rmd file would be useful

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/lesson-example#57]
It's useful having the 01-introduction.md file. It would also be useful to have an example file for the Rmd. Also having that file would let the 'make lesson-rmd' command be tested.

**Comment by gvwilson** [comment]
Is `_episodes_rmd/06-rmarkdown-example.Rmd` what you want?

**Comment by tracykteal** [comment]
Yes, good, just missed it somehow.
