### ISSUE TITLE
Make setup instructions more visible

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/lesson-example#66]
Can we add a link to setup on the begin of the Schedule? Is difficult to remember that the setup instructions are on the top nav bar.

**Comment by njamescouk** [comment]
+1 This has caught me out at least once.

**Comment by gcapes** [comment]
I think it makes more sense to put it in the pre-requisites, but agree it should be mentioned.

**Comment by mkuzak** [comment]
+1 I agree, it's easy to miss.

**Comment by qjcg** [comment]
In favor as well.

**Comment by gdevenyi** [comment]
+1

**Comment by k8hertweck** [comment]
+1

**Comment by kubu4** [comment]
Agreed with @gcapes. For a user visiting the site and beginning The Unix Shell, there's nothing to indicate that any set up is needed at all.

**Comment by rgaiacs** [comment]
@k8hertweck How do you want to handle https://github.com/swcarpentry/styles/pull/110?

**Comment by daattali** [comment]
+1 I also came here to suggest this. It took me a long time to realize there is a setup page. It should be mentioned on the table of contents page
