### ISSUE TITLE
Writing R markdown lessons: challenges and callouts

### ISSUE THREAD

**Issue by sritchie73** [swcarpentry/lesson-example#7]
Knitr code chunks do not work in the challenge, callout, or any other "blockquote" sections. 

In the latest R novice gapminder lessons (https://github.com/swcarpentry/r-novice-gapminder/pull/24), I've written these chunks using the standard markdown code and {.output} blocks. 

What are the rest of the R community doing? If this is reasonable, LAYOUT.md needs to be updated to include these instructions.

**Comment by fmichonneau** [comment]
Hi Scott,

That was a "bug" in knitr and is now fixed in the latest version available
on GitHub.

  -- François

**Comment by abought** [comment]
@sritchie73, does updating your Knitr version resolve the problem reported? If so, should we update documentation to reflect the version requirement?

**Comment by gvwilson** [comment]
Is this still a problem with the new template?

**Comment by fmichonneau** [comment]
This has been fixed for a while (https://github.com/swcarpentry/lesson-template/pull/271) and it won't be a problem with the new template. @sritchie73 feel free to re-open if you still notice any issues.
