### ISSUE TITLE
Should lessons exercises require solutions?

### ISSUE THREAD

**Issue by daattali** [swcarpentry/lesson-example#72]
When a person creates a lesson exercise, they should presumably know the correct answer to the exercise. I've noticed that some exercises have solutions (the first few episodes of the unix lesson for example), but the vast majority do not.  Is there a reason to not include the solutions?

I find it useful for both learners and instructors: learners will want to see solutions if they go through an episode that was not taught in their workshop, and instructors will benefit from having confirmation that their idea of the correct answer is indeed correct.

**Comment by rgaiacs** [comment]
Hi @daattali. Thanks for the issue.

>  Is there a reason to not include the solutions?

When we started insert exercises we didn't required the exercise to have a solution. Later we started to include it but they are still a work in progress. :-( Any contribution to help us get to 100% of exercises with solution is welcome.

> I find it useful for both learners and instructors: learners will want to see solutions if they go through an episode that was not taught in their workshop, and instructors will benefit from having confirmation that their idea of the correct answer is indeed correct.

We agree with you.

I'm closing this. You can open issues for exercises with missing solution on the issue track of the respective lesson.
