### ISSUE TITLE
Item 12 link to 'episodes of the lesson' is 404ing

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/lesson-example#74]

**Comment by gvwilson** [comment]
Thanks for the PR - can you please tell us which page contains the broken link? The only place with an 'item 12' is <http://swcarpentry.github.io/lesson-example/setup/>, but the link <http://swcarpentry.github.io/lesson-example/#schedule> seems to resolve correctly.

**Comment by tracykteal** [comment]
It's fine now. Yesterday it was 404ing for some reason. All good.
