### ISSUE TITLE
YAML typo in _episodes/04-formatting.md

### ISSUE THREAD

**Issue by byandell** [swcarpentry/lesson-example#81]
In the YAML for file
https://github.com/swcarpentry/lesson-example/blob/gh-pages/_episodes/04-formatting.md

the keypoints has the following line:
"Code blocks can be have the source, regular output, or error class."

Probably "can be have" should either be "can be" or "have"

**Comment by rgaiacs** [comment]
@byandell Thanks for the issue and sorry for the delay to fix this one.
