### ISSUE TITLE
typo in _episodes_rmd/06-rmarkdown-example.Rmd

### ISSUE THREAD

**Issue by byandell** [swcarpentry/lesson-example#82]
https://github.com/swcarpentry/lesson-example/blob/gh-pages/_episodes_rmd/06-rmarkdown-example.Rmd
After the figure there is the line:

"For the challenges and their solutions, you need to pay attention to the where the > go"

One of the "the"s needs to go (the first).

Also, would be good to but back quotes around >, as in `>`

**Comment by fmichonneau** [comment]
thanks @byandell 

I fixed the typo and the tick marks around the > were already part a PR waiting to be merged.
