### ISSUE TITLE
Add "Edit on GitHub"

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/lesson-example#99]
Raw of proof concept screenshot

![screencapture-localhost-4000-01-design-1486401948765](https://cloud.githubusercontent.com/assets/1506457/22658253/61b1e974-ec91-11e6-8465-d3c1d57097a6.png)

This is related with https://github.com/swcarpentry/lesson-example/pull/97 and the discussion of how to increase contributions to the lessons.

In the [past](https://github.com/swcarpentry/DEPRECATED-site/issues/448) we used [GitHub Ribbons](https://github.com/blog/273-github-ribbons) but this was deprecated on the new style for one reason that I don't know.

cc @ErinBecker

**Comment by wking** [comment]
On Mon, Feb 06, 2017 at 09:30:03AM -0800, Raniere Silva wrote:
> In the past we used GitHub Ribbons, but this was deprecated on the
> new style for one reason that I don't know.

I think we should use the ribbons (they're a more familiar UI than
rolling our own), but we probably want to make this fix in
swcarpentry/styles so both lessons and workshops can share it.
Workshop repos get less development, but putting the ribbon up there
is still useful as a “look, we dogfood this stuff” example to
learners.
